#!/bin/bash

environment=$(echo $APPLICATION_ENV)
wd=$(dirname $0)
wd=$(realpath $wd)
suffix=$(date | sed -E 's/\s/-/g' | sed -E 's/:/-/g')
archive_filename="database_backups".$suffix.zip
timestamp=$(date +%s)
methods=('email' 'copy' 'scp')

echo "Working directory: $wd"
cd $wd

#include functions
source func

#does ini file exist?
if ! test -f conf.ini; then
  echo "conf.ini does not exist."
  exit 1;
fi

#read ini values
source <(grep = conf.ini)

echo "Backup Method: $method"

#Validate configuration
validateConfig

#make temp directory
echo "Creating temp directory temp/ ..."
mkdir -p temp

echo "Databases: ${databases[*]}"

for database in "${databases[@]}"
do
	suffix=$(date | sed -E 's/\s/-/g' | sed -E 's/:/-/g')
	out_filename=$database.$suffix.sql

	echo "Dumping $database ..."	
	mysqldump --defaults-file=$mysql_defaults_file \
				--add-drop-database \
				--dump-date \
				--events \
				--add-drop-table \
				--default-character-set=utf8 \
				--routines=true \
				--events \
				--databases $database > temp/$out_filename
	status=$?

	if [[ $status -ne 0 ]]; then
		echo "Failed to dump database '$database'."
		exit 1
	fi

	zip -u temp/$archive_filename temp/$out_filename
				
done

case $method in

  'copy')
	#copy archive
	#create copy path is not exist
	mkdir -p $copy_to
	cp temp/$archive_filename $copy_to 
    
	status=$?

	if [[ $status -ne 0 ]]; then
		echo "Failed to copy temp/$archive_filename to $copy_to"
		exit 1
	fi
    ;;

  'scp')
	#scp archive
    	echo "Copying temp/$archive_filename to $scp_user@$scp_host:$scp_path ..."
    	
    	#set scp_port to 22 if it is not set
    	if [[ -z "$scp_port" ]]; then
		scp_port=22
	fi
    
    	scp -p -i $scp_identity_file -P $scp_port temp/$archive_filename $scp_user@$scp_host:$scp_path
    	
    	status=$?

	if [[ $status -ne 0 ]]; then
		echo "Failed to copy temp/$archive_filename to $scp_user@$scp_host:$scp_path"
		exit 1
	fi
    ;;

  *)
    #email archive
	emailDatabasesArchive
    ;;
esac

	
cleanup

echo "Done!";
